name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger_jenkins_job:
    runs-on: [ self-hosted, macOS ]

    steps:
    - name: Run Jenkins Job
      env:
        JENKINS_URL: ${{secrets.JENKINS_BASE_URL}}
        JENKINS_USER: ${{ secrets.JENKINS_USER_NAME }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        JENKINS_JOB_NAME: ${{ secrets.JENKINS_GITHUB_ACTION_JOB_NAME }}
      run: |
        curl -X POST ${JENKINS_URL}/job/${JENKINS_JOB_NAME}/build \
             --user ${JENKINS_USER}:${JENKINS_TOKEN}
