name: Trigger Jenkins Job

on:
  workflow_dispatch:

jobs:
  trigger_jenkins_job:
    runs-on: [ self-hosted, macOS ]

    steps:
     
    - name: Run Jenkins Job
      env:
        JENKINS_URL: ${{secrets.JENKINS_BASE_URL}}
        JENKINS_USER: ${{ secrets.JENKINS_USER_NAME }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        JENKINS_JOB_NAME: ${{ secrets.JENKINS_GITHUB_ACTION_JOB_NAME }}
  
      run: | 
       echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
       curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"parameter": [{"name": "BRANCH_NAME", "value": "'$BRANCH_NAME'"}]}' \
              ${JENKINS_URL}/job/${JENKINS_JOB_NAME}/build
               --user ${JENKINS_USER}:${JENKINS_TOKEN}
